import { getPlantById } from "./PlantDatabase";

const mergedPlants = [
  {
    "id": "annona_phaeoclados_mart",
    "scientificName": "Annona phaeoclados Mart.",
    "commonNamePt": " ATA- VERMELHA ",
    "alternativeNamesPt": [],
    "family": "Annonaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "duguetia_furfuracea_sthil_bet_h",
    "scientificName": "Duguetia furfuracea (St.Hil.) B.et H.",
    "commonNamePt": " ATA-BRAVA ",
    "alternativeNamesPt": [
      "ata-de-lobo"
    ],
    "family": "Annonaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "himatanthus_obovatus_margwoods",
    "scientificName": "Himatanthus obovatus (M.Arg.)Woods.",
    "commonNamePt": "ANGÉLICA",
    "alternativeNamesPt": [
      "pau-de-leite"
    ],
    "family": "Apocynaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "annona_dioica_st_hil",
    "scientificName": "Annona dioica St. Hil.",
    "commonNamePt": "ARIXICUM",
    "alternativeNamesPt": [
      "ariticurn"
    ],
    "family": "Annonaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "rollinia_emarginata_schl",
    "scientificName": "Rollinia emarginata Schl.",
    "commonNamePt": "ARIXICUM-DO-MATO",
    "alternativeNamesPt": [],
    "family": "Annonaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "myracrodruon_urundeuva_engl_frall",
    "scientificName": "Myracrodruon urundeuva (Engl.) Fr.All.",
    "commonNamePt": "AROEIRA",
    "alternativeNamesPt": [],
    "family": "Anacardiaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "annona_cornifolia_st_hil",
    "scientificName": "Annona cornifolia St. Hil.",
    "commonNamePt": "ATA-DE-COBRA",
    "alternativeNamesPt": [
      "atinha-do-campo"
    ],
    "family": "Annonaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "justicia_gendarussa_burm_f",
    "scientificName": "Justicia gendarussa Burm. f.",
    "commonNamePt": "Abre caminho",
    "alternativeNamesPt": [],
    "family": "Acanthaceae",
    "origin": "**X**",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "rosmarinus_officinalis_l",
    "scientificName": "Rosmarinus officinalis L.",
    "commonNamePt": "Alecrim",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "ocimum_campechianum_mill",
    "scientificName": "Ocimum campechianum Mill.",
    "commonNamePt": "Alfavaca de jardim / Chá-da-Índia / Canelinha",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "lavandula_dentata_l",
    "scientificName": "Lavandula dentata L.",
    "commonNamePt": "Alfazema francesa",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Europa",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "lavandula_angustifolia_mill",
    "scientificName": "Lavandula angustifolia Mill.",
    "commonNamePt": "Alfazema inglesa",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Europa",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "allium_tuberosum_rottler_ex_spreng",
    "scientificName": "Allium tuberosum Rottler ex Spreng",
    "commonNamePt": "Alho Nirá",
    "alternativeNamesPt": [],
    "family": "Amaryllidaceae",
    "origin": "Sudeste asiático",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "alstroemeria_cf_psittacina_lehm",
    "scientificName": "Alstroemeria cf. psittacina Lehm.",
    "commonNamePt": "",
    "alternativeNamesPt": [],
    "family": "Amaryllidaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "bryophyllum_daigremontianum_raym_hamet_&_hperrier_aberger",
    "scientificName": "Bryophyllum daigremontianum (Raym.-Hamet & H.Perrier) A.Berger",
    "commonNamePt": "Aranto",
    "alternativeNamesPt": [],
    "family": "Crassulaceae",
    "origin": "Madacascar",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "solidago_chilensis_meyen",
    "scientificName": "Solidago chilensis Meyen",
    "commonNamePt": "Arnica brasileira",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "América do Sul",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "ruta_graveolens_l",
    "scientificName": "Ruta graveolens L.",
    "commonNamePt": "Arruda",
    "alternativeNamesPt": [],
    "family": "Rutaceae",
    "origin": "Europa meridional",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "vernonia_polyanthes_less",
    "scientificName": "Vernonia polyanthes Less.",
    "commonNamePt": "Assa-peixe",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Brasil",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "euphorbia_tirucalli_l",
    "scientificName": "Euphorbia tirucalli L.",
    "commonNamePt": "Avelós",
    "alternativeNamesPt": [],
    "family": "Euphorbiaceae",
    "origin": "Madacascar",
    "habit": "Arbórea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "curcuma_longa_l",
    "scientificName": "Curcuma longa L.",
    "commonNamePt": "Açafrão",
    "alternativeNamesPt": [],
    "family": "Zingiberaceae",
    "origin": "Ásia (Índia, Indonésia)",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "aristolochia_esperanzae_kze",
    "scientificName": "Aristolochia esperanzae Kze.",
    "commonNamePt": "BUTA",
    "alternativeNamesPt": [],
    "family": "Aristolochiaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "aloe_vera_l_burm_f",
    "scientificName": "Aloe vera (L.) Burm. f.",
    "commonNamePt": "Babosa",
    "alternativeNamesPt": [],
    "family": "Asphodelaceae",
    "origin": "África",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "aloe_arborescens_mill",
    "scientificName": "Aloe arborescens Mill.",
    "commonNamePt": "Babosa folha fina",
    "alternativeNamesPt": [],
    "family": "Asphodelaceae",
    "origin": "África",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "plectranthus_ornatus_codd",
    "scientificName": "Plectranthus ornatus Codd.",
    "commonNamePt": "Boldinho",
    "alternativeNamesPt": [
      "boldo chinês"
    ],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo / Oriente Próximo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "plectranthus_barbatus_andrews",
    "scientificName": "Plectranthus barbatus Andrews",
    "commonNamePt": "Boldo",
    "alternativeNamesPt": [
      "Boldo brasileiro",
      "Boldo da terra"
    ],
    "family": "Lamiaceae",
    "origin": "Região Paleotropical",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "plectranthus_neochilus_schltr",
    "scientificName": "Plectranthus neochilus Schltr.",
    "commonNamePt": "Boldo miúdo",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "África do Sul",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "vernonia_condensata_baker",
    "scientificName": "Vernonia condensata Baker",
    "commonNamePt": "Boldo-da-Bahia",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "África",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "bonafousia_siphilitica_lf_l_allorge",
    "scientificName": "Bonafousia siphilitica (L.f.) L. Allorge",
    "commonNamePt": "",
    "alternativeNamesPt": [],
    "family": "Apocynaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "sedum_dendroideum_moc_&_sessé_ex_dc",
    "scientificName": "Sedum dendroideum Moc & Sessé ex DC",
    "commonNamePt": "Bálsamo",
    "alternativeNamesPt": [],
    "family": "Crassulaceae",
    "origin": "México",
    "habit": "",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "spondias_lutea_l",
    "scientificName": "Spondias lutea L.",
    "commonNamePt": "CAIA",
    "alternativeNamesPt": [
      "cajá",
      "cajazeira",
      "acaiá"
    ],
    "family": "Anacardiaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "stenandrium_pohlii_nees",
    "scientificName": "Stenandrium pohlii Nees",
    "commonNamePt": "CAIAPIÁ",
    "alternativeNamesPt": [
      "carapiá"
    ],
    "family": "Acanthaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "anacardium_humile_st_hil",
    "scientificName": "Anacardium humile St. Hil.",
    "commonNamePt": "CAJUZINHO",
    "alternativeNamesPt": [
      "cajuzinho-do-campo",
      "caju-do-cerrado",
      "cajuí"
    ],
    "family": "Anacardiaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "achyranthes_aspera_l",
    "scientificName": "Achyranthes aspera L.",
    "commonNamePt": "CARRAPICHO",
    "alternativeNamesPt": [
      "rabo-de-coati",
      "carrapicho-praga",
      "prega-prega"
    ],
    "family": "Amaranthaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "glinus_radiatus_l",
    "scientificName": "Glinus radiatus L.",
    "commonNamePt": "CARURU-DO-BREJO",
    "alternativeNamesPt": [],
    "family": "Aizoaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "amaranthus_lividus_l_ssp_polygonoides",
    "scientificName": "Amaranthus lividus L. ssp. polygonoides",
    "commonNamePt": "CARURU-DO-BREJO",
    "alternativeNamesPt": [],
    "family": "Amaranthaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "rhabdadenia_pohlii_marg",
    "scientificName": "Rhabdadenia pohlii M.Arg.",
    "commonNamePt": "CIPÓ- LEITEIRO-DA-FOLHA-FINA ",
    "alternativeNamesPt": [],
    "family": "Apocynaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "secondatia_densiflora_dc",
    "scientificName": "Secondatia densiflora DC.",
    "commonNamePt": "CIPÓ-DE-LEITE",
    "alternativeNamesPt": [],
    "family": "Apocynaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "prestonia_coalita_vellwoods",
    "scientificName": "Prestonia coalita (Vell.)Woods.",
    "commonNamePt": "CIPÓZINHO-DE-LEITE",
    "alternativeNamesPt": [],
    "family": "Apocynaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "calendula_officinalis_l",
    "scientificName": "Calendula officinalis L.",
    "commonNamePt": "Calêndula",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Europa central",
    "habit": "",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "matricaria_chamomilla_l",
    "scientificName": "Matricaria chamomilla L.",
    "commonNamePt": "Camomila",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "artemisia_alba_turra",
    "scientificName": "Artemisia alba Turra",
    "commonNamePt": "Canforeiro",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "cymbopogon_citratus_dc_stapf",
    "scientificName": "Cymbopogon citratus (DC.) Stapf",
    "commonNamePt": "Capim Cidreira",
    "alternativeNamesPt": [
      "capim limão"
    ],
    "family": "Poaceae",
    "origin": "Sudoeste Asiático",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "baccharis_trimera_less_dc",
    "scientificName": "Baccharis trimera (Less.) DC.",
    "commonNamePt": "Carqueja",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Andes Peruano / América do Sul",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "chenopodium_ambrosioides_l",
    "scientificName": "Chenopodium ambrosioides L.",
    "commonNamePt": "Erva de Santa Maria",
    "alternativeNamesPt": [],
    "family": "Amaranthaceae",
    "origin": "América central e do Sul",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "justicia_pectoralis_jacq_var_stenophylla",
    "scientificName": "Justicia pectoralis Jacq. var. stenophylla",
    "commonNamePt": "Chambá",
    "alternativeNamesPt": [
      "Anador",
      "Trevo cumaru",
      "Melhoral"
    ],
    "family": "Acanthaceae",
    "origin": "América Tropical",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "lippia_alba_mill_ne_br_ex_britton_&_p_wilson",
    "scientificName": "Lippia alba (Mill.) N.E. Br. ex Britton & P. Wilson",
    "commonNamePt": "Cidrila",
    "alternativeNamesPt": [],
    "family": "Verbenaceae",
    "origin": "Brasil",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "cymbopogon_nardus",
    "scientificName": "Cymbopogon nardus",
    "commonNamePt": "Citronela",
    "alternativeNamesPt": [],
    "family": "Poaceae",
    "origin": "Ásia tropical",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "cosmos_caudatus_kunth",
    "scientificName": "Cosmos caudatus Kunth",
    "commonNamePt": "Cosmos",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Américas",
    "habit": "",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "foeniculum_vulgare_miller",
    "scientificName": "Foeniculum vulgare Miller",
    "commonNamePt": "Funcho",
    "alternativeNamesPt": [
      "Erva-doce brasileira"
    ],
    "family": "Apiaceae",
    "origin": "Mediterrâneo (Europa mediterrânea, Norte da África e Ásia ocidental)",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "zingiber_officinale_roscoe",
    "scientificName": "Zingiber officinale Roscoe",
    "commonNamePt": "Gengibre",
    "alternativeNamesPt": [],
    "family": "Zingiberaceae",
    "origin": "Ásia",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "stachytarpheta_cayennensis_rich_vahl",
    "scientificName": "Stachytarpheta cayennensis (Rich.) Vahl",
    "commonNamePt": "Gervejão",
    "alternativeNamesPt": [],
    "family": "Verbenaceae",
    "origin": "América Tropical",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "tithonia_diversifolia_hemsl_a_gray",
    "scientificName": "Tithonia diversifolia (Hemsl.) A. Gray",
    "commonNamePt": "Girassol mexicano",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "México",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "mikania_glomerata_spreng",
    "scientificName": "Mikania glomerata Spreng",
    "commonNamePt": "Guaco",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "América do Sul[ ]()",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "petiveria_alliacea_l",
    "scientificName": "Petiveria alliacea L.",
    "commonNamePt": "Guiné",
    "alternativeNamesPt": [],
    "family": "Phytolaccaceae",
    "origin": "Brasil",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "mentha_x_piperita_l",
    "scientificName": "Mentha x piperita L.",
    "commonNamePt": "Hortelã",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "mentha_sp_1",
    "scientificName": "Mentha sp. 1",
    "commonNamePt": "Hortelã",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "mentha_sp_2",
    "scientificName": "Mentha sp. 2",
    "commonNamePt": "Hortelã",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "plectranthus_amboinicus_lour_spreng",
    "scientificName": "Plectranthus amboinicus (Lour.) Spreng.",
    "commonNamePt": "Hortelã-da-folha-grossa",
    "alternativeNamesPt": [
      "Malva-de-cheiro"
    ],
    "family": "Lamiaceae",
    "origin": "Ilha de Amboin (Nova Guiné)",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "mentha_sp",
    "scientificName": "Mentha sp.",
    "commonNamePt": "Hortelã variegata",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "",
    "habit": "",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "cissus_verticillata_l_nicolson_&_ce_jarvis",
    "scientificName": "Cissus verticillata (L.) Nicolson & C.E. Jarvis",
    "commonNamePt": "Insulina",
    "alternativeNamesPt": [
      "anil-trepador",
      "uva-do-mato"
    ],
    "family": "Vitaceae",
    "origin": "Brasil",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "ziziphus_joazeiro_mart",
    "scientificName": "Ziziphus joazeiro Mart.",
    "commonNamePt": "Juazeiro",
    "alternativeNamesPt": [],
    "family": "Rhamnaceae",
    "origin": "Brasil",
    "habit": "Arbórea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "lantana_camara_l",
    "scientificName": "Lantana camara L.",
    "commonNamePt": "Lantana",
    "alternativeNamesPt": [],
    "family": "Verbenaceae",
    "origin": "Brasil",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "mentha_sylvestris_l",
    "scientificName": "Mentha sylvestris L.",
    "commonNamePt": "Levante",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "hippeastrum_puniceum_lam_o_kuntze",
    "scientificName": "Hippeastrum puniceum (Lam.) O. Kuntze",
    "commonNamePt": "LÍRIO",
    "alternativeNamesPt": [
      "beladona"
    ],
    "family": "Amaryllidaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "artemisia_absinthium_l",
    "scientificName": "Artemisia absinthium L.",
    "commonNamePt": "Losna",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "achyrocline_satureioides_lam_dc",
    "scientificName": "Achyrocline satureioides (Lam.) DC.",
    "commonNamePt": "Macelinha",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Nativa",
    "habit": "",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "pelargonium_citrosum_voigt_ex_breiter",
    "scientificName": "Pelargonium citrosum Voigt ex Breiter",
    "commonNamePt": "Malva rosa",
    "alternativeNamesPt": [],
    "family": "Geraniaceae",
    "origin": "Sul da África",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "ocimum_basilicum_l",
    "scientificName": "Ocimum basilicum L.",
    "commonNamePt": "Manjericão",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "ocimum_basilicum_l_var_purpureum_hort",
    "scientificName": "Ocimum basilicum L. var. purpureum Hort.",
    "commonNamePt": "Manjericão Roxo",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "origanum_majorana_l",
    "scientificName": "Origanum majorana L.",
    "commonNamePt": "Manjerona",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "passiflora_sp",
    "scientificName": "Passiflora sp.",
    "commonNamePt": "Maracujá",
    "alternativeNamesPt": [],
    "family": "Passifloraceae",
    "origin": "",
    "habit": "",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "melissa_officinalis_l",
    "scientificName": "Melissa officinalis L.",
    "commonNamePt": "Melissa",
    "alternativeNamesPt": [
      "Erva Cidreira Verdadeira"
    ],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "achillea_millefolium_l",
    "scientificName": "Achillea millefolium L.",
    "commonNamePt": "Mil folhas",
    "alternativeNamesPt": [
      "anador",
      "novalgina"
    ],
    "family": "Asteraceae",
    "origin": "Europa e Ásia ocidental",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "origanum_vulgare_l",
    "scientificName": "Origanum vulgare L.",
    "commonNamePt": "Orégano",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Sul da Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "capsicum_chinense_jacq",
    "scientificName": "Capsicum chinense Jacq.",
    "commonNamePt": "Pimenta Biquinho",
    "alternativeNamesPt": [],
    "family": "Solanaceae",
    "origin": "Américas",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "xylopia_aromatica_lam_mart",
    "scientificName": "Xylopia aromatica (Lam. ) Mart.",
    "commonNamePt": "PINDAÍVA",
    "alternativeNamesPt": [
      "pindaíba",
      "Pimenta-de-macaco."
    ],
    "family": "Annonaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "unonopsis_lindmanii_fries",
    "scientificName": "Unonopsis lindmanii Fries",
    "commonNamePt": "PINDAÍVA-PRETA",
    "alternativeNamesPt": [
      "carrapateira",
      "pindaíva-do-brejo",
      "café"
    ],
    "family": "Annonaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "mentha_pulegium_l",
    "scientificName": "Mentha pulegium L.",
    "commonNamePt": "Poejo",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Europa, Ásia e península arábica",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "iresine_macrophyla_r_e_fries",
    "scientificName": "Iresine macrophyla R.E.Fries",
    "commonNamePt": "POMBEIRO-BRANCO",
    "alternativeNamesPt": [],
    "family": "Amaranthaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "phyllanthus_niruri_l",
    "scientificName": "Phyllanthus niruri L.",
    "commonNamePt": "Quebra-pedra",
    "alternativeNamesPt": [],
    "family": "Phyllanthaceae",
    "origin": "Tropical",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "schinopsis_balansae_engl",
    "scientificName": "Schinopsis balansae Engl.",
    "commonNamePt": "QUEBRACHO",
    "alternativeNamesPt": [
      "quebracho-vermelho"
    ],
    "family": "Anacardiaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "aspidosperma_quebracho_blanco_schl",
    "scientificName": "Aspidosperma quebracho-blanco Schl.",
    "commonNamePt": "QUEBRACHO-BRANCO",
    "alternativeNamesPt": [
      "quina"
    ],
    "family": "Apocynaceae",
    "origin": "Pantanal (Embrapa)",
    "habit": "",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa"
  },
  {
    "id": "salvia_officinalis_l",
    "scientificName": "Salvia officinalis L.",
    "commonNamePt": "Salvia",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "stevia_rebaudiana_bertoni_bertoni",
    "scientificName": "Stevia rebaudiana (Bertoni) Bertoni",
    "commonNamePt": "Stevia",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Brasil",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "tanacetum_vulgare_l",
    "scientificName": "Tanacetum vulgare L.",
    "commonNamePt": "Tanaceto",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "plantago_major_l",
    "scientificName": "Plantago major L.",
    "commonNamePt": "Tanchagem",
    "alternativeNamesPt": [],
    "family": "Plantaginaceae",
    "origin": "Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "solanum_betaceum_cav",
    "scientificName": "Solanum betaceum Cav.",
    "commonNamePt": "Tomate de árvore",
    "alternativeNamesPt": [],
    "family": "Solanaceae",
    "origin": "América do Sul (Bolívia e Peru)",
    "habit": "Arboreto",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  },
  {
    "id": "curcuma_zedoaria_christm_roscoe",
    "scientificName": "Curcuma zedoaria (Christm.) Roscoe",
    "commonNamePt": "Zedoária / Açafrão roxo",
    "alternativeNamesPt": [],
    "family": "Zingiberaceae",
    "origin": "Índia",
    "habit": "",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS"
  }
];

export const plantDatabase = mergedPlants.map(plant => {
  // Ensure commonNamePt is always a string
  if (typeof plant.commonNamePt !== 'string') {
    plant.commonNamePt = String(plant.commonNamePt || '');
  }
  // Ensure alternativeNamesPt is always an array of strings
  if (!Array.isArray(plant.alternativeNamesPt)) {
    plant.alternativeNamesPt = [];
  }
  plant.alternativeNamesPt = plant.alternativeNamesPt.map(name => String(name || ''));

  return plant;
});

// Função para buscar plantas por nome português
export const searchPlantsByPortuguese = (query) => {
  const searchTerm = query.toLowerCase().trim();
  
  return plantDatabase.filter(plant => {
    const commonName = plant.commonNamePt.toLowerCase();
    const alternatives = plant.alternativeNamesPt.map(name => name.toLowerCase());
    
    return commonName.includes(searchTerm) || 
           alternatives.some(alt => alt.includes(searchTerm));
  });
};

// Função para buscar plantas por nome científico
export const searchPlantsByScientific = (query) => {
  const searchTerm = query.toLowerCase().trim();
  
  return plantDatabase.filter(plant => 
    plant.scientificName.toLowerCase().includes(searchTerm)
  );
};

// Função para buscar planta por ID
export const getPlantById = (id) => {
  return plantDatabase.find(plant => plant.id === id);
};

// Função para buscar planta por nome científico exato
export const getPlantByScientificName = (scientificName) => {
  return plantDatabase.find(plant => 
    plant.scientificName.toLowerCase() === scientificName.toLowerCase()
  );
};

// Função para obter todas as plantas ordenadas por nome português
export const getAllPlantsOrderedByPortuguese = () => {
  return [...plantDatabase].sort((a, b) => 
    a.commonNamePt.localeCompare(b.commonNamePt, 'pt-BR')
  );
};

