// PlantDatabase.js
// Simula um banco de dados local de plantas
// Você pode carregar esses dados de um arquivo JSON ou de uma API no futuro.

const mergedPlants = [
  {
    "id": "annona_phaeoclados_mart",
    "scientificName": "Annona phaeoclados Mart.",
    "commonNamePt": "Ata-vermelha",
    "alternativeNamesPt": [],
    "family": "Annonaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "duguetia_furfuracea_sthil_bet_h",
    "scientificName": "Duguetia furfuracea (St.Hil.) B.et H.",
    "commonNamePt": "Ata-brava",
    "alternativeNamesPt": [
      "ata-de-lobo"
    ],
    "family": "Annonaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "himatanthus_obovatus_margwoods",
    "scientificName": "Himatanthus obovatus (M.Arg.)Woods.",
    "commonNamePt": "Angélica",
    "alternativeNamesPt": [
      "pau-de-leite"
    ],
    "family": "Apocynaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "annona_dioica_st_hil",
    "scientificName": "Annona dioica St. Hil.",
    "commonNamePt": "Arixicum",
    "alternativeNamesPt": [
      "ariticurn"
    ],
    "family": "Annonaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "rollinia_emarginata_schl",
    "scientificName": "Rollinia emarginata Schl.",
    "commonNamePt": "Arixicum-do-mato",
    "alternativeNamesPt": [],
    "family": "Annonaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "myracrodruon_urundeuva_engl_frall",
    "scientificName": "Myracrodruon urundeuva (Engl.) Fr.All.",
    "commonNamePt": "Aroeira",
    "alternativeNamesPt": [],
    "family": "Anacardiaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "annona_cornifolia_st_hil",
    "scientificName": "Annona cornifolia St. Hil.",
    "commonNamePt": "Ata-de-cobra",
    "alternativeNamesPt": [
      "atinha-do-campo"
    ],
    "family": "Annonaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "justicia_gendarussa_burm_f",
    "scientificName": "Justicia gendarussa Burm. f.",
    "commonNamePt": "Abre caminho",
    "alternativeNamesPt": [],
    "family": "Acanthaceae",
    "origin": "Desconhecida", // Corrigido
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "rosmarinus_officinalis_l",
    "scientificName": "Rosmarinus officinalis L.",
    "commonNamePt": "Alecrim",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "ocimum_campechianum_mill",
    "scientificName": "Ocimum campechianum Mill.",
    "commonNamePt": "Alfavaca de jardim", // Simplificado para o primeiro nome, os outros podem ir para alternativeNamesPt
    "alternativeNamesPt": ["Chá-da-Índia", "Canelinha"],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "lavandula_dentata_l",
    "scientificName": "Lavandula dentata L.",
    "commonNamePt": "Alfazema francesa",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Europa",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "lavandula_angustifolia_mill",
    "scientificName": "Lavandula angustifolia Mill.",
    "commonNamePt": "Alfazema inglesa",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Europa",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "allium_tuberosum_rottler_ex_spreng",
    "scientificName": "Allium tuberosum Rottler ex Spreng",
    "commonNamePt": "Alho Nirá",
    "alternativeNamesPt": [],
    "family": "Amaryllidaceae",
    "origin": "Sudeste asiático",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "alstroemeria_cf_psittacina_lehm",
    "scientificName": "Alstroemeria cf. psittacina Lehm.",
    "commonNamePt": "Alstroemeria", // Adicionado commonNamePt se estava em branco
    "alternativeNamesPt": [],
    "family": "Amaryllidaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "bryophyllum_daigremontianum_raym_hamet_&_hperrier_aberger",
    "scientificName": "Bryophyllum daigremontianum (Raym.-Hamet & H.Perrier) A.Berger",
    "commonNamePt": "Aranto",
    "alternativeNamesPt": [],
    "family": "Crassulaceae",
    "origin": "Madagascar", // Corrigido a grafia
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "solidago_chilensis_meyen",
    "scientificName": "Solidago chilensis Meyen",
    "commonNamePt": "Arnica brasileira",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "América do Sul",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "ruta_graveolens_l",
    "scientificName": "Ruta graveolens L.",
    "commonNamePt": "Arruda",
    "alternativeNamesPt": [],
    "family": "Rutaceae",
    "origin": "Europa meridional",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "vernonia_polyanthes_less",
    "scientificName": "Vernonia polyanthes Less.",
    "commonNamePt": "Assa-peixe",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Brasil",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "euphorbia_tirucalli_l",
    "scientificName": "Euphorbia tirucalli L.",
    "commonNamePt": "Avelós",
    "alternativeNamesPt": [],
    "family": "Euphorbiaceae",
    "origin": "Madagascar", // Corrigido a grafia
    "habit": "Arbórea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "curcuma_longa_l",
    "scientificName": "Curcuma longa L.",
    "commonNamePt": "Açafrão",
    "alternativeNamesPt": [],
    "family": "Zingiberaceae",
    "origin": "Ásia (Índia, Indonésia)",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "aristolochia_esperanzae_kze",
    "scientificName": "Aristolochia esperanzae Kze.",
    "commonNamePt": "Butá",
    "alternativeNamesPt": [],
    "family": "Aristolochiaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "aloe_vera_l_burm_f",
    "scientificName": "Aloe vera (L.) Burm. f.",
    "commonNamePt": "Babosa",
    "alternativeNamesPt": [],
    "family": "Asphodelaceae",
    "origin": "África",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "aloe_arborescens_mill",
    "scientificName": "Aloe arborescens Mill.",
    "commonNamePt": "Babosa folha fina",
    "alternativeNamesPt": [],
    "family": "Asphodelaceae",
    "origin": "África",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "plectranthus_ornatus_codd",
    "scientificName": "Plectranthus ornatus Codd.",
    "commonNamePt": "Boldinho",
    "alternativeNamesPt": [
      "boldo chinês"
    ],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo / Oriente Próximo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "plectranthus_barbatus_andrews",
    "scientificName": "Plectranthus barbatus Andrews",
    "commonNamePt": "Boldo",
    "alternativeNamesPt": [
      "Boldo brasileiro",
      "Boldo da terra"
    ],
    "family": "Lamiaceae",
    "origin": "Região Paleotropical",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "plectranthus_neochilus_schltr",
    "scientificName": "Plectranthus neochilus Schltr.",
    "commonNamePt": "Boldo miúdo",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "África do Sul",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "vernonia_condensata_baker",
    "scientificName": "Vernonia condensata Baker",
    "commonNamePt": "Boldo-da-Bahia",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "África",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "bonafousia_siphilitica_lf_l_allorge",
    "scientificName": "Bonafousia siphilitica (L.f.) L. Allorge",
    "commonNamePt": "Bonafousia siphilitica", // Adicionado commonNamePt se estava em branco
    "alternativeNamesPt": [],
    "family": "Apocynaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "sedum_dendroideum_moc_&_sessé_ex_dc",
    "scientificName": "Sedum dendroideum Moc & Sessé ex DC",
    "commonNamePt": "Bálsamo",
    "alternativeNamesPt": [],
    "family": "Crassulaceae",
    "origin": "México",
    "habit": "Não informado",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "spondias_lutea_l",
    "scientificName": "Spondias lutea L.",
    "commonNamePt": "Cajá", // Mudado para o nome mais comum, os outros em alternativeNamesPt
    "alternativeNamesPt": [
      "cajazeira",
      "acaiá",
      "Caia" // Mantido o original como alternativa
    ],
    "family": "Anacardiaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "stenandrium_pohlii_nees",
    "scientificName": "Stenandrium pohlii Nees",
    "commonNamePt": "Caiapiá",
    "alternativeNamesPt": [
      "carapiá"
    ],
    "family": "Acanthaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "anacardium_humile_st_hil",
    "scientificName": "Anacardium humile St. Hil.",
    "commonNamePt": "Cajuzinho",
    "alternativeNamesPt": [
      "cajuzinho-do-campo",
      "caju-do-cerrado",
      "cajuí"
    ],
    "family": "Anacardiaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "achyranthes_aspera_l",
    "scientificName": "Achyranthes aspera L.",
    "commonNamePt": "Carrapicho",
    "alternativeNamesPt": [
      "rabo-de-coati",
      "carrapicho-praga",
      "prega-prega"
    ],
    "family": "Amaranthaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "glinus_radiatus_l",
    "scientificName": "Glinus radiatus L.",
    "commonNamePt": "Caruru-do-brejo",
    "alternativeNamesPt": [],
    "family": "Aizoaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "amaranthus_lividus_l_ssp_polygonoides",
    "scientificName": "Amaranthus lividus L. ssp. polygonoides",
    "commonNamePt": "Caruru-do-brejo",
    "alternativeNamesPt": [],
    "family": "Amaranthaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "rhabdadenia_pohlii_marg",
    "scientificName": "Rhabdadenia pohlii M.Arg.",
    "commonNamePt": "Cipó-leiteiro-da-folha-fina",
    "alternativeNamesPt": [],
    "family": "Apocynaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "secondatia_densiflora_dc",
    "scientificName": "Secondatia densiflora DC.",
    "commonNamePt": "Cipó-de-leite",
    "alternativeNamesPt": [],
    "family": "Apocynaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "prestonia_coalita_vellwoods",
    "scientificName": "Prestonia coalita (Vell.)Woods.",
    "commonNamePt": "Cipózinho-de-leite",
    "alternativeNamesPt": [],
    "family": "Apocynaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "calendula_officinalis_l",
    "scientificName": "Calendula officinalis L.",
    "commonNamePt": "Calêndula",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Europa central",
    "habit": "Não informado",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "matricaria_chamomilla_l",
    "scientificName": "Matricaria chamomilla L.",
    "commonNamePt": "Camomila",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "artemisia_alba_turra",
    "scientificName": "Artemisia alba Turra",
    "commonNamePt": "Canforeiro",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "cymbopogon_citratus_dc_stapf",
    "scientificName": "Cymbopogon citratus (DC.) Stapf",
    "commonNamePt": "Capim Cidreira",
    "alternativeNamesPt": [
      "capim limão"
    ],
    "family": "Poaceae",
    "origin": "Sudoeste asiático",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "baccharis_trimera_less_dc",
    "scientificName": "Baccharis trimera (Less.) DC.",
    "commonNamePt": "Carqueja",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Andes Peruano / América do Sul",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "chenopodium_ambrosioides_l",
    "scientificName": "Chenopodium ambrosioides L.",
    "commonNamePt": "Erva de Santa Maria",
    "alternativeNamesPt": [],
    "family": "Amaranthaceae",
    "origin": "América Central e do Sul",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "justicia_pectoralis_jacq_var_stenophylla",
    "scientificName": "Justicia pectoralis Jacq. var. stenophylla",
    "commonNamePt": "Chambá",
    "alternativeNamesPt": [
      "Anador",
      "Trevo cumaru",
      "Melhoral"
    ],
    "family": "Acanthaceae",
    "origin": "América Tropical",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "lippia_alba_mill_ne_br_ex_britton_&_p_wilson",
    "scientificName": "Lippia alba (Mill.) N.E. Br. ex Britton & P. Wilson",
    "commonNamePt": "Cidrila",
    "alternativeNamesPt": [],
    "family": "Verbenaceae",
    "origin": "Brasil",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "cymbopogon_nardus",
    "scientificName": "Cymbopogon nardus",
    "commonNamePt": "Citronela",
    "alternativeNamesPt": [],
    "family": "Poaceae",
    "origin": "Ásia tropical",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "cosmos_caudatus_kunth",
    "scientificName": "Cosmos caudatus Kunth",
    "commonNamePt": "Cosmos",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Américas",
    "habit": "Não informado",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "foeniculum_vulgare_miller",
    "scientificName": "Foeniculum vulgare Miller",
    "commonNamePt": "Funcho",
    "alternativeNamesPt": [
      "Erva-doce brasileira"
    ],
    "family": "Apiaceae",
    "origin": "Mediterrâneo (Europa mediterrânea, Norte da África e Ásia ocidental)",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "zingiber_officinale_roscoe",
    "scientificName": "Zingiber officinale Roscoe",
    "commonNamePt": "Gengibre",
    "alternativeNamesPt": [],
    "family": "Zingiberaceae",
    "origin": "Ásia",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "stachytarpheta_cayennensis_rich_vahl",
    "scientificName": "Stachytarpheta cayennensis (Rich.) Vahl",
    "commonNamePt": "Gervejão",
    "alternativeNamesPt": [],
    "family": "Verbenaceae",
    "origin": "América Tropical",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "tithonia_diversifolia_hemsl_a_gray",
    "scientificName": "Tithonia diversifolia (Hemsl.) A. Gray",
    "commonNamePt": "Girassol mexicano",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "México",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "mikania_glomerata_spreng",
    "scientificName": "Mikania glomerata Spreng",
    "commonNamePt": "Guaco",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "América do Sul",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "petiveria_alliacea_l",
    "scientificName": "Petiveria alliacea L.",
    "commonNamePt": "Guiné",
    "alternativeNamesPt": [],
    "family": "Phytolaccaceae",
    "origin": "Brasil",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "mentha_x_piperita_l",
    "scientificName": "Mentha x piperita L.",
    "commonNamePt": "Hortelã",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "mentha_sp_1",
    "scientificName": "Mentha sp. 1",
    "commonNamePt": "Hortelã (Tipo 1)", // Diferenciado para evitar ID duplicado visualmente
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "mentha_sp_2",
    "scientificName": "Mentha sp. 2",
    "commonNamePt": "Hortelã (Tipo 2)", // Diferenciado para evitar ID duplicado visualmente
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "plectranthus_amboinicus_lour_spreng",
    "scientificName": "Plectranthus amboinicus (Lour.) Spreng.",
    "commonNamePt": "Hortelã-da-folha-grossa",
    "alternativeNamesPt": [
      "Malva-de-cheiro"
    ],
    "family": "Lamiaceae",
    "origin": "Ilha de Amboin (Nova Guiné)",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "mentha_sp_variegata", // ID mais específico
    "scientificName": "Mentha sp.",
    "commonNamePt": "Hortelã variegata",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Não informado",
    "habit": "Não informado",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "cissus_verticillata_l_nicolson_&_ce_jarvis",
    "scientificName": "Cissus verticillata (L.) Nicolson & C.E. Jarvis",
    "commonNamePt": "Insulina",
    "alternativeNamesPt": [
      "anil-trepador",
      "uva-do-mato"
    ],
    "family": "Vitaceae",
    "origin": "Brasil",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "ziziphus_joazeiro_mart",
    "scientificName": "Ziziphus joazeiro Mart.",
    "commonNamePt": "Juazeiro",
    "alternativeNamesPt": [],
    "family": "Rhamnaceae",
    "origin": "Brasil",
    "habit": "Arbórea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "lantana_camara_l",
    "scientificName": "Lantana camara L.",
    "commonNamePt": "Lantana",
    "alternativeNamesPt": [],
    "family": "Verbenaceae",
    "origin": "Brasil",
    "habit": "Arbustiva",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "mentha_sylvestris_l",
    "scientificName": "Mentha sylvestris L.",
    "commonNamePt": "Levante",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "hippeastrum_puniceum_lam_o_kuntze",
    "scientificName": "Hippeastrum puniceum (Lam.) O. Kuntze",
    "commonNamePt": "Lírio",
    "alternativeNamesPt": [
      "beladona"
    ],
    "family": "Amaryllidaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "artemisia_absinthium_l",
    "scientificName": "Artemisia absinthium L.",
    "commonNamePt": "Losna",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Europa e Ásia ocidental",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "achyrocline_satureioides_lam_dc",
    "scientificName": "Achyrocline satureioides (Lam.) DC.",
    "commonNamePt": "Macelinha",
    "alternativeNamesPt": [],
    "family": "Asteraceae",
    "origin": "Nativa",
    "habit": "Não informado",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "pelargonium_citrosum_voigt_ex_breiter",
    "scientificName": "Pelargonium citrosum Voigt ex Breiter",
    "commonNamePt": "Malva rosa",
    "alternativeNamesPt": [],
    "family": "Geraniaceae",
    "origin": "Sul da África",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "ocimum_basilicum_l",
    "scientificName": "Ocimum basilicum L.",
    "commonNamePt": "Manjericão",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "ocimum_basilicum_l_var_purpureum_hort",
    "scientificName": "Ocimum basilicum L. var. purpureum Hort.",
    "commonNamePt": "Manjericão Roxo",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "origanum_majorana_l",
    "scientificName": "Origanum majorana L.",
    "commonNamePt": "Manjerona",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "passiflora_sp",
    "scientificName": "Passiflora sp.",
    "commonNamePt": "Maracujá",
    "alternativeNamesPt": [],
    "family": "Passifloraceae",
    "origin": "Não informado",
    "habit": "Não informado",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "melissa_officinalis_l",
    "scientificName": "Melissa officinalis L.",
    "commonNamePt": "Melissa",
    "alternativeNamesPt": [
      "Erva Cidreira Verdadeira"
    ],
    "family": "Lamiaceae",
    "origin": "Mediterrâneo",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "achillea_millefolium_l",
    "scientificName": "Achillea millefolium L.",
    "commonNamePt": "Mil folhas",
    "alternativeNamesPt": [
      "anador",
      "novalgina"
    ],
    "family": "Asteraceae",
    "origin": "Europa e Ásia ocidental",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": true,
    "farmacopeia": true,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "origanum_vulgare_l",
    "scientificName": "Origanum vulgare L.",
    "commonNamePt": "Orégano",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Sul da Europa",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "capsicum_chinense_jacq",
    "scientificName": "Capsicum chinense Jacq.",
    "commonNamePt": "Pimenta Biquinho",
    "alternativeNamesPt": [],
    "family": "Solanaceae",
    "origin": "Américas",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "xylopia_aromatica_lam_mart",
    "scientificName": "Xylopia aromatica (Lam. ) Mart.",
    "commonNamePt": "Pindaíva",
    "alternativeNamesPt": [
      "pindaíba",
      "Pimenta-de-macaco."
    ],
    "family": "Annonaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "unonopsis_lindmanii_fries",
    "scientificName": "Unonopsis lindmanii Fries",
    "commonNamePt": "Pindaíva-preta",
    "alternativeNamesPt": [
      "carrapateira",
      "pindaíva-do-brejo",
      "café"
    ],
    "family": "Annonaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  },
  {
    "id": "mentha_pulegium_l",
    "scientificName": "Mentha pulegium L.",
    "commonNamePt": "Poejo",
    "alternativeNamesPt": [],
    "family": "Lamiaceae",
    "origin": "Europa, Ásia e península arábica",
    "habit": "Herbácea",
    "biodiversa": true,
    "dermatologica": true,
    "hoca": true,
    "renisus": false,
    "farmacopeia": false,
    "source": "IFSULDEMINAS",
    "imageUrl": null
  },
  {
    "id": "iresine_macrophyla_r_e_fries",
    "scientificName": "Iresine macrophyla R.E.Fries",
    "commonNamePt": "Pombeiro-branco",
    "alternativeNamesPt": [],
    "family": "Amaranthaceae",
    "origin": "Brasil (Pantanal)",
    "habit": "Não informado",
    "biodiversa": false,
    "dermatologica": false,
    "hoca": false,
    "renisus": false,
    "farmacopeia": false,
    "source": "Embrapa",
    "imageUrl": null
  }
];

// Funções de busca
export const searchPlantsByPortuguese = (query) => {
  const lowerCaseQuery = query.toLowerCase();
  return mergedPlants.filter(plant =>
    (plant.commonNamePt && plant.commonNamePt.toLowerCase().includes(lowerCaseQuery)) ||
    (plant.alternativeNamesPt && plant.alternativeNamesPt.some(name => name.toLowerCase().includes(lowerCaseQuery)))
  );
};

export const searchPlantsByScientific = (query) => {
  const lowerCaseQuery = query.toLowerCase();
  return mergedPlants.filter(plant =>
    (plant.scientificName && plant.scientificName.toLowerCase().includes(lowerCaseQuery))
  );
};

export const getPlantById = (id) => {
  return mergedPlants.find(plant => plant.id === id);
};

export const getAllPlantsOrderedByPortuguese = () => {
  // Cria uma cópia para não modificar o array original e ordena
  return [...mergedPlants].sort((a, b) =>
    (a.commonNamePt || '').localeCompare((b.commonNamePt || ''), 'pt-BR', { sensitivity: 'base' })
  );
};

// Array completo para outros propósitos
export default mergedPlants;